// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO133bbaZIzTfIvKfq73xc-LIrNLq2ngo',
    appId: '1:939439499093:web:ef759de8b6ab5d5132f1dc',
    messagingSenderId: '939439499093',
    projectId: 'sirius-49d79',
    authDomain: 'sirius-49d79.firebaseapp.com',
    storageBucket: 'sirius-49d79.appspot.com',
    measurementId: 'G-KN8BKWB5XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-cdTsUHz3Feoir5ftSuKI5B6ybHJ8UHg',
    appId: '1:939439499093:android:43ffb71334c931de32f1dc',
    messagingSenderId: '939439499093',
    projectId: 'sirius-49d79',
    storageBucket: 'sirius-49d79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP6tn9Q7_D_qxXpbsMoBGnojgs_kFLM4w',
    appId: '1:939439499093:ios:cf98550976b0fd1532f1dc',
    messagingSenderId: '939439499093',
    projectId: 'sirius-49d79',
    storageBucket: 'sirius-49d79.appspot.com',
    iosClientId: '939439499093-ki3cr62kdjbef3ti4p7nkcth3kus04rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirius23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP6tn9Q7_D_qxXpbsMoBGnojgs_kFLM4w',
    appId: '1:939439499093:ios:cf98550976b0fd1532f1dc',
    messagingSenderId: '939439499093',
    projectId: 'sirius-49d79',
    storageBucket: 'sirius-49d79.appspot.com',
    iosClientId: '939439499093-ki3cr62kdjbef3ti4p7nkcth3kus04rl.apps.googleusercontent.com',
    iosBundleId: 'com.example.sirius23',
  );
}
