name: sirius23
description: Firebase & Testing lectures

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase auth dependencies
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4
  # Service locator
  get_it: ^7.2.0
  #
  cloud_firestore: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
